# Generated by Django 5.2 on 2025-04-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-13 00:00:00'),
            preserve_default=False,
        ),
    ]
